name: Docker Image CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'releases/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Retrieve version
      run: |
        echo ::set-env name=VERSION::$(cat VERSION)
        echo ::set-env name=VCS_REF::$(git rev-parse HEAD)
        echo ::set-env name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.4.0
      with:
        build-args: |
          BUILD_DATE=${{ env.BUILD_DATE }}
          VCS_REF=${{ env.VCS_REF }}
          VERSION=${{ env.VERSION }}
        push: true
        tags: localgod/ansible-lint:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

